.class public final LX/5Va;
.super Ljava/lang/Object;
.source ""


# direct methods
.method public static final A00(LX/1dd;LX/469;LX/2tk;LX/6AH;Lcom/instagram/service/session/UserSession;)Ljava/util/ArrayList;
    .locals 8

    .line 0
    const/4 v5, 0x1

    .line 1
    invoke-static {p0, v5}, LX/02K;->A0A(Ljava/lang/Object;I)V

    .line 2
    .line 3
    .line 4
    const/4 v0, 0x2

    .line 5
    invoke-static {p2, v0}, LX/02K;->A0A(Ljava/lang/Object;I)V

    .line 6
    .line 7
    .line 8
    const/4 v0, 0x4

    .line 9
    invoke-static {p4, v0}, LX/02K;->A0A(Ljava/lang/Object;I)V

    .line 10
    .line 11
    .line 12
    iget-object v4, p1, LX/469;->A0I:Lcom/instagram/model/reels/Reel;

    .line 13
    .line 14
    iget-object v0, v4, Lcom/instagram/model/reels/Reel;->A13:Ljava/util/Map;

    .line 15
    .line 16
    new-instance v3, Ljava/util/ArrayList;

    .line 17
    .line 18
    invoke-direct {v3}, Ljava/util/ArrayList;-><init>()V

    .line 19
    .line 20
    .line 21
    invoke-interface {v0}, Ljava/util/Map;->entrySet()Ljava/util/Set;

    .line 22
    .line 23
    .line 24
    move-result-object v0

    .line 25
    invoke-interface {v0}, Ljava/util/Set;->iterator()Ljava/util/Iterator;

    .line 26
    .line 27
    .line 28
    move-result-object v7

    .line 29
    :goto_0
    invoke-interface {v7}, Ljava/util/Iterator;->hasNext()Z

    .line 30
    .line 31
    .line 32
    move-result v0

    .line 33
    if-eqz v0, :cond_10

    .line 34
    .line 35
    invoke-interface {v7}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    .line 36
    .line 37
    .line 38
    move-result-object v0

    .line 39
    check-cast v0, Ljava/util/Map$Entry;

    .line 40
    .line 41
    invoke-interface {v0}, Ljava/util/Map$Entry;->getKey()Ljava/lang/Object;

    .line 42
    .line 43
    .line 44
    move-result-object v6

    .line 45
    check-cast v6, LX/1dV;

    .line 46
    .line 47
    invoke-interface {v0}, Ljava/util/Map$Entry;->getValue()Ljava/lang/Object;

    .line 48
    .line 49
    .line 50
    move-result-object v2

    .line 51
    check-cast v2, Ljava/lang/Number;

    .line 52
    .line 53
    if-eqz v6, :cond_0

    .line 54
    .line 55
    sget-object v1, LX/5Vb;->A00:[I

    .line 56
    .line 57
    invoke-virtual {v6}, Ljava/lang/Enum;->ordinal()I

    .line 58
    .line 59
    .line 60
    move-result v0

    .line 61
    aget v0, v1, v0

    .line 62
    .line 63
    packed-switch v0, :pswitch_data_0

    .line 64
    .line 65
    .line 66
    :cond_0
    invoke-static {v6}, LX/02K;->A03(Ljava/lang/Object;)V

    .line 67
    .line 68
    .line 69
    invoke-static {v2}, LX/02K;->A03(Ljava/lang/Object;)V

    .line 70
    .line 71
    .line 72
    invoke-virtual {v2}, Ljava/lang/Number;->intValue()I

    .line 73
    .line 74
    .line 75
    move-result v0

    .line 76
    invoke-static {v6, v0}, LX/5Va;->A01(LX/1dV;I)Ljava/util/HashMap;

    .line 77
    .line 78
    .line 79
    move-result-object v2

    .line 80
    :goto_1
    invoke-virtual {v3, v2}, Ljava/util/AbstractCollection;->add(Ljava/lang/Object;)Z

    .line 81
    .line 82
    .line 83
    goto :goto_0

    .line 84
    :pswitch_0
    invoke-static {v2}, LX/02K;->A03(Ljava/lang/Object;)V

    .line 85
    .line 86
    .line 87
    invoke-virtual {v2}, Ljava/lang/Number;->intValue()I

    .line 88
    .line 89
    .line 90
    move-result v6

    .line 91
    sget-object v2, LX/1dV;->A0F:LX/1dV;

    .line 92
    .line 93
    invoke-static {p0}, LX/69w;->A09(LX/1dd;)Z

    .line 94
    .line 95
    .line 96
    move-result v0

    .line 97
    if-nez v0, :cond_9

    .line 98
    .line 99
    const v6, 0x9eb11

    .line 100
    .line 101
    .line 102
    goto/16 :goto_2

    .line 103
    .line 104
    :pswitch_1
    invoke-static {v2}, LX/02K;->A03(Ljava/lang/Object;)V

    .line 105
    .line 106
    .line 107
    invoke-virtual {v2}, Ljava/lang/Number;->intValue()I

    .line 108
    .line 109
    .line 110
    move-result v6

    .line 111
    iget-object v1, v4, Lcom/instagram/model/reels/Reel;->A0v:Ljava/util/List;

    .line 112
    .line 113
    sget-object v2, LX/1dV;->A02:LX/1dV;

    .line 114
    .line 115
    if-eqz v1, :cond_1

    .line 116
    .line 117
    sget-object v0, Lcom/instagram/model/reels/sponsored/AutoGeneratedCardType;->A03:Lcom/instagram/model/reels/sponsored/AutoGeneratedCardType;

    .line 118
    .line 119
    invoke-interface {v1, v0}, Ljava/util/List;->contains(Ljava/lang/Object;)Z

    .line 120
    .line 121
    .line 122
    move-result v0

    .line 123
    if-ne v0, v5, :cond_1

    .line 124
    .line 125
    goto/16 :goto_2

    .line 126
    .line 127
    :cond_1
    invoke-virtual {p0}, LX/1dd;->A0H()LX/5YS;

    .line 128
    .line 129
    .line 130
    move-result-object v0

    .line 131
    if-eqz v0, :cond_2

    .line 132
    .line 133
    invoke-virtual {p0}, LX/1dd;->A0H()LX/5YS;

    .line 134
    .line 135
    .line 136
    move-result-object v0

    .line 137
    if-eqz v0, :cond_2

    .line 138
    .line 139
    iget-object v0, v0, LX/5YS;->A07:Ljava/lang/String;

    .line 140
    .line 141
    if-eqz v0, :cond_2

    .line 142
    .line 143
    invoke-virtual {v0}, Ljava/lang/String;->length()I

    .line 144
    .line 145
    .line 146
    move-result v1

    .line 147
    if-eqz v1, :cond_2

    .line 148
    .line 149
    const/16 v0, 0x190

    .line 150
    .line 151
    const v6, 0xa1225

    .line 152
    .line 153
    .line 154
    if-lt v0, v1, :cond_9

    .line 155
    .line 156
    :cond_2
    const v6, 0xa1221

    .line 157
    .line 158
    .line 159
    goto/16 :goto_2

    .line 160
    .line 161
    :pswitch_2
    invoke-static {v2}, LX/02K;->A03(Ljava/lang/Object;)V

    .line 162
    .line 163
    .line 164
    invoke-virtual {v2}, Ljava/lang/Number;->intValue()I

    .line 165
    .line 166
    .line 167
    move-result v6

    .line 168
    sget-object v2, LX/1dV;->A03:LX/1dV;

    .line 169
    .line 170
    invoke-static {p0, p1}, LX/69w;->A0C(LX/1dd;LX/469;)Z

    .line 171
    .line 172
    .line 173
    move-result v0

    .line 174
    if-nez v0, :cond_9

    .line 175
    .line 176
    const v6, 0xcd141

    .line 177
    .line 178
    .line 179
    goto/16 :goto_2

    .line 180
    .line 181
    :pswitch_3
    invoke-static {v2}, LX/02K;->A03(Ljava/lang/Object;)V

    .line 182
    .line 183
    .line 184
    invoke-virtual {v2}, Ljava/lang/Number;->intValue()I

    .line 185
    .line 186
    .line 187
    move-result v6

    .line 188
    sget-object v2, LX/1dV;->A04:LX/1dV;

    .line 189
    .line 190
    invoke-static {p0, p1, p2, p3, p4}, LX/69w;->A0E(LX/1dd;LX/469;LX/2tk;LX/6AH;Lcom/instagram/service/session/UserSession;)Z

    .line 191
    .line 192
    .line 193
    move-result v0

    .line 194
    if-nez v0, :cond_9

    .line 195
    .line 196
    const v6, 0xbe6e1

    .line 197
    .line 198
    .line 199
    goto/16 :goto_2

    .line 200
    .line 201
    :pswitch_4
    invoke-static {v2}, LX/02K;->A03(Ljava/lang/Object;)V

    .line 202
    .line 203
    .line 204
    invoke-virtual {v2}, Ljava/lang/Number;->intValue()I

    .line 205
    .line 206
    .line 207
    move-result v6

    .line 208
    sget-object v2, LX/1dV;->A0A:LX/1dV;

    .line 209
    .line 210
    invoke-static {p0}, LX/69w;->A08(LX/1dd;)Z

    .line 211
    .line 212
    .line 213
    move-result v0

    .line 214
    if-nez v0, :cond_9

    .line 215
    .line 216
    const v6, 0xc3501

    .line 217
    .line 218
    .line 219
    goto/16 :goto_2

    .line 220
    .line 221
    :pswitch_5
    invoke-static {v2}, LX/02K;->A03(Ljava/lang/Object;)V

    .line 222
    .line 223
    .line 224
    invoke-virtual {v2}, Ljava/lang/Number;->intValue()I

    .line 225
    .line 226
    .line 227
    move-result v6

    .line 228
    invoke-static {p0}, LX/69w;->A0A(LX/1dd;)Z

    .line 229
    .line 230
    .line 231
    move-result v0

    .line 232
    if-nez v0, :cond_3

    .line 233
    .line 234
    const v6, 0x113e11

    .line 235
    .line 236
    .line 237
    :cond_3
    sget-object v2, LX/1dV;->A0G:LX/1dV;

    .line 238
    .line 239
    goto/16 :goto_2

    .line 240
    .line 241
    :pswitch_6
    invoke-static {v2}, LX/02K;->A03(Ljava/lang/Object;)V

    .line 242
    .line 243
    .line 244
    invoke-virtual {v2}, Ljava/lang/Number;->intValue()I

    .line 245
    .line 246
    .line 247
    move-result v6

    .line 248
    sget-object v2, LX/1dV;->A08:LX/1dV;

    .line 249
    .line 250
    invoke-virtual {p0}, LX/1dd;->A1U()Z

    .line 251
    .line 252
    .line 253
    move-result v0

    .line 254
    if-nez v0, :cond_9

    .line 255
    .line 256
    const v6, 0x129da1

    .line 257
    .line 258
    .line 259
    goto/16 :goto_2

    .line 260
    .line 261
    :pswitch_7
    invoke-static {v2}, LX/02K;->A03(Ljava/lang/Object;)V

    .line 262
    .line 263
    .line 264
    invoke-virtual {v2}, Ljava/lang/Number;->intValue()I

    .line 265
    .line 266
    .line 267
    move-result v6

    .line 268
    sget-object v2, LX/1dV;->A0J:LX/1dV;

    .line 269
    .line 270
    invoke-virtual {p0}, LX/1dd;->A0H()LX/5YS;

    .line 271
    .line 272
    .line 273
    move-result-object v0

    .line 274
    if-eqz v0, :cond_4

    .line 275
    .line 276
    iget-object v0, v0, LX/5YS;->A08:Ljava/lang/String;

    .line 277
    .line 278
    if-eqz v0, :cond_4

    .line 279
    .line 280
    goto/16 :goto_2

    .line 281
    .line 282
    :cond_4
    const v6, 0x1312d1

    .line 283
    .line 284
    .line 285
    goto/16 :goto_2

    .line 286
    .line 287
    :pswitch_8
    invoke-static {v2}, LX/02K;->A03(Ljava/lang/Object;)V

    .line 288
    .line 289
    .line 290
    invoke-virtual {v2}, Ljava/lang/Number;->intValue()I

    .line 291
    .line 292
    .line 293
    move-result v6

    .line 294
    invoke-virtual {p0}, LX/1dd;->A0H()LX/5YS;

    .line 295
    .line 296
    .line 297
    move-result-object v1

    .line 298
    const/4 v0, 0x0

    .line 299
    if-eqz v1, :cond_5

    .line 300
    .line 301
    iget-object v0, v1, LX/5YS;->A07:Ljava/lang/String;

    .line 302
    .line 303
    :cond_5
    const/4 v1, 0x0

    .line 304
    if-eqz v0, :cond_6

    .line 305
    .line 306
    invoke-virtual {v0}, Ljava/lang/String;->length()I

    .line 307
    .line 308
    .line 309
    move-result v0

    .line 310
    if-eqz v0, :cond_6

    .line 311
    .line 312
    invoke-virtual {p0}, LX/1dd;->A0H()LX/5YS;

    .line 313
    .line 314
    .line 315
    move-result-object v0

    .line 316
    if-eqz v0, :cond_6

    .line 317
    .line 318
    iget-object v0, v0, LX/5YS;->A00:Lcom/facebook/kotlin/compilerplugins/dataclassgenerate/superclass/KtCSuperShape0S0100000_I0;

    .line 319
    .line 320
    if-eqz v0, :cond_6

    .line 321
    .line 322
    const/4 v1, 0x1

    .line 323
    :cond_6
    sget-object v2, LX/1dV;->A0B:LX/1dV;

    .line 324
    .line 325
    if-nez v1, :cond_9

    .line 326
    .line 327
    const v6, 0x13fd31

    .line 328
    .line 329
    .line 330
    goto :goto_2

    .line 331
    :pswitch_9
    invoke-static {v2}, LX/02K;->A03(Ljava/lang/Object;)V

    .line 332
    .line 333
    .line 334
    invoke-virtual {v2}, Ljava/lang/Number;->intValue()I

    .line 335
    .line 336
    .line 337
    move-result v6

    .line 338
    sget-object v2, LX/1dV;->A0C:LX/1dV;

    .line 339
    .line 340
    invoke-virtual {p0}, LX/1dd;->A15()Z

    .line 341
    .line 342
    .line 343
    move-result v0

    .line 344
    if-nez v0, :cond_9

    .line 345
    .line 346
    const v6, 0x147261

    .line 347
    .line 348
    .line 349
    goto :goto_2

    .line 350
    :pswitch_a
    invoke-static {v2}, LX/02K;->A03(Ljava/lang/Object;)V

    .line 351
    .line 352
    .line 353
    invoke-virtual {v2}, Ljava/lang/Number;->intValue()I

    .line 354
    .line 355
    .line 356
    move-result v6

    .line 357
    iget-object v1, v4, Lcom/instagram/model/reels/Reel;->A0v:Ljava/util/List;

    .line 358
    .line 359
    sget-object v2, LX/1dV;->A09:LX/1dV;

    .line 360
    .line 361
    if-eqz v1, :cond_7

    .line 362
    .line 363
    sget-object v0, Lcom/instagram/model/reels/sponsored/AutoGeneratedCardType;->A05:Lcom/instagram/model/reels/sponsored/AutoGeneratedCardType;

    .line 364
    .line 365
    invoke-interface {v1, v0}, Ljava/util/List;->contains(Ljava/lang/Object;)Z

    .line 366
    .line 367
    .line 368
    move-result v0

    .line 369
    if-ne v0, v5, :cond_7

    .line 370
    .line 371
    goto :goto_2

    .line 372
    :cond_7
    const v6, 0x1535b1

    .line 373
    .line 374
    .line 375
    goto :goto_2

    .line 376
    :pswitch_b
    invoke-static {v2}, LX/02K;->A03(Ljava/lang/Object;)V

    .line 377
    .line 378
    .line 379
    invoke-virtual {v2}, Ljava/lang/Number;->intValue()I

    .line 380
    .line 381
    .line 382
    move-result v6

    .line 383
    sget-object v2, LX/1dV;->A0I:LX/1dV;

    .line 384
    .line 385
    iget-object v0, p0, LX/1dd;->A0K:LX/1M5;

    .line 386
    .line 387
    if-eqz v0, :cond_8

    .line 388
    .line 389
    iget-object v0, v0, LX/1M5;->A0d:LX/1MC;

    .line 390
    .line 391
    iget-object v0, v0, LX/1MC;->A00:Lcom/facebook/kotlin/compilerplugins/dataclassgenerate/superclass/KtCSuperShape0S0100000_I0;

    .line 392
    .line 393
    if-eqz v0, :cond_8

    .line 394
    .line 395
    iget-object v0, v0, Lcom/facebook/kotlin/compilerplugins/dataclassgenerate/superclass/KtCSuperShape0S0100000_I0;->A00:Ljava/lang/Object;

    .line 396
    .line 397
    if-eqz v0, :cond_8

    .line 398
    .line 399
    goto :goto_2

    .line 400
    :cond_8
    const v6, 0x19a281

    .line 401
    .line 402
    .line 403
    goto :goto_2

    .line 404
    :pswitch_c
    invoke-static {v2}, LX/02K;->A03(Ljava/lang/Object;)V

    .line 405
    .line 406
    .line 407
    invoke-virtual {v2}, Ljava/lang/Number;->intValue()I

    .line 408
    .line 409
    .line 410
    move-result v6

    .line 411
    iget-object v1, v4, Lcom/instagram/model/reels/Reel;->A0v:Ljava/util/List;

    .line 412
    .line 413
    sget-object v2, LX/1dV;->A0D:LX/1dV;

    .line 414
    .line 415
    if-eqz v1, :cond_a

    .line 416
    .line 417
    sget-object v0, Lcom/instagram/model/reels/sponsored/AutoGeneratedCardType;->A06:Lcom/instagram/model/reels/sponsored/AutoGeneratedCardType;

    .line 418
    .line 419
    invoke-interface {v1, v0}, Ljava/util/List;->contains(Ljava/lang/Object;)Z

    .line 420
    .line 421
    .line 422
    move-result v0

    .line 423
    if-ne v0, v5, :cond_a

    .line 424
    .line 425
    :cond_9
    :goto_2
    invoke-static {v2, v6}, LX/5Va;->A01(LX/1dV;I)Ljava/util/HashMap;

    .line 426
    .line 427
    .line 428
    move-result-object v2

    .line 429
    goto/16 :goto_1

    .line 430
    .line 431
    :cond_a
    const v6, 0x1a17b1

    .line 432
    .line 433
    .line 434
    goto :goto_2

    .line 435
    :pswitch_d
    new-instance v2, Ljava/util/HashMap;

    .line 436
    .line 437
    invoke-direct {v2}, Ljava/util/HashMap;-><init>()V

    .line 438
    .line 439
    .line 440
    const-string v1, "44"

    .line 441
    .line 442
    const-string v0, "optimization_type"

    .line 443
    .line 444
    invoke-virtual {v2, v0, v1}, Ljava/util/AbstractMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    .line 445
    .line 446
    .line 447
    iget-object v0, v4, Lcom/instagram/model/reels/Reel;->A11:Ljava/util/List;

    .line 448
    .line 449
    if-eqz v0, :cond_b

    .line 450
    .line 451
    invoke-interface {v0}, Ljava/util/List;->size()I

    .line 452
    .line 453
    .line 454
    move-result v1

    .line 455
    :goto_3
    const v0, 0x6b6c0

    .line 456
    .line 457
    .line 458
    goto :goto_6

    .line 459
    :cond_b
    const/4 v1, 0x1

    .line 460
    goto :goto_3

    .line 461
    :pswitch_e
    new-instance v2, Ljava/util/HashMap;

    .line 462
    .line 463
    invoke-direct {v2}, Ljava/util/HashMap;-><init>()V

    .line 464
    .line 465
    .line 466
    const-string v1, "98"

    .line 467
    .line 468
    const-string v0, "optimization_type"

    .line 469
    .line 470
    invoke-virtual {v2, v0, v1}, Ljava/util/AbstractMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    .line 471
    .line 472
    .line 473
    iget-object v0, v4, Lcom/instagram/model/reels/Reel;->A11:Ljava/util/List;

    .line 474
    .line 475
    if-eqz v0, :cond_c

    .line 476
    .line 477
    invoke-interface {v0}, Ljava/util/List;->size()I

    .line 478
    .line 479
    .line 480
    move-result v1

    .line 481
    :goto_4
    const v0, 0xef420

    .line 482
    .line 483
    .line 484
    goto :goto_6

    .line 485
    :cond_c
    const/4 v1, 0x1

    .line 486
    goto :goto_4

    .line 487
    :pswitch_f
    sget-object v2, LX/1dV;->A07:LX/1dV;

    .line 488
    .line 489
    invoke-virtual {p0}, LX/1dd;->A0I()LX/5YS;

    .line 490
    .line 491
    .line 492
    move-result-object v1

    .line 493
    if-eqz v1, :cond_d

    .line 494
    .line 495
    iget-object v0, v1, LX/5YS;->A07:Ljava/lang/String;

    .line 496
    .line 497
    invoke-static {v0}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z

    .line 498
    .line 499
    .line 500
    move-result v0

    .line 501
    if-nez v0, :cond_d

    .line 502
    .line 503
    iget-boolean v1, v1, LX/5YS;->A0A:Z

    .line 504
    .line 505
    const v0, 0x35b61

    .line 506
    .line 507
    .line 508
    if-nez v1, :cond_e

    .line 509
    .line 510
    :cond_d
    const v0, 0x35b62

    .line 511
    .line 512
    .line 513
    :cond_e
    invoke-static {v2, v0}, LX/5Va;->A01(LX/1dV;I)Ljava/util/HashMap;

    .line 514
    .line 515
    .line 516
    move-result-object v2

    .line 517
    goto/16 :goto_1

    .line 518
    .line 519
    :pswitch_10
    new-instance v2, Ljava/util/HashMap;

    .line 520
    .line 521
    invoke-direct {v2}, Ljava/util/HashMap;-><init>()V

    .line 522
    .line 523
    .line 524
    const-string v1, "23"

    .line 525
    .line 526
    const-string v0, "optimization_type"

    .line 527
    .line 528
    invoke-virtual {v2, v0, v1}, Ljava/util/AbstractMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    .line 529
    .line 530
    .line 531
    invoke-static {p1, p4}, LX/469;->A00(LX/469;Lcom/instagram/service/session/UserSession;)Ljava/util/List;

    .line 532
    .line 533
    .line 534
    move-result-object v0

    .line 535
    invoke-interface {v0}, Ljava/util/List;->size()I

    .line 536
    .line 537
    .line 538
    move-result v6

    .line 539
    iget v1, v4, Lcom/instagram/model/reels/Reel;->A00:I

    .line 540
    .line 541
    invoke-virtual {v4, p4}, Lcom/instagram/model/reels/Reel;->A0x(Lcom/instagram/service/session/UserSession;)Z

    .line 542
    .line 543
    .line 544
    move-result v0

    .line 545
    if-eqz v0, :cond_f

    .line 546
    .line 547
    if-ltz v1, :cond_f

    .line 548
    .line 549
    add-int/lit8 v1, v1, 0x1

    .line 550
    .line 551
    if-ge v1, v6, :cond_f

    .line 552
    .line 553
    :goto_5
    const v0, 0x38270

    .line 554
    .line 555
    .line 556
    :goto_6
    add-int/2addr v1, v0

    .line 557
    invoke-static {v1}, Ljava/lang/String;->valueOf(I)Ljava/lang/String;

    .line 558
    .line 559
    .line 560
    move-result-object v1

    .line 561
    const-string v0, "option_value"

    .line 562
    .line 563
    invoke-virtual {v2, v0, v1}, Ljava/util/AbstractMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    .line 564
    .line 565
    .line 566
    goto/16 :goto_1

    .line 567
    .line 568
    :cond_f
    move v1, v6

    .line 569
    goto :goto_5

    .line 570
    :cond_10
    return-object v3

    .line 571
    nop

    .line 572
    :pswitch_data_0
    .packed-switch 0x1
        :pswitch_d
        :pswitch_e
        :pswitch_f
        :pswitch_0
        :pswitch_1
        :pswitch_10
        :pswitch_2
        :pswitch_3
        :pswitch_4
        :pswitch_5
        :pswitch_6
        :pswitch_7
        :pswitch_8
        :pswitch_9
        :pswitch_a
        :pswitch_b
        :pswitch_c
    .end packed-switch
    .line 573
    .line 574
    .line 575
    .line 576
    .line 577
    .line 578
    .line 579
    .line 580
    .line 581
    .line 582
    .line 583
    .line 584
    .line 585
    .line 586
    .line 587
    .line 588
    .line 589
    .line 590
    .line 591
    .line 592
    .line 593
    .line 594
    .line 595
    .line 596
    .line 597
    .line 598
    .line 599
    .line 600
    .line 601
    .line 602
    .line 603
    .line 604
    .line 605
    .line 606
    .line 607
    .line 608
    .line 609
    .line 610
    .line 611
    .line 612
    .line 613
    .line 614
    .line 615
    .line 616
    .line 617
    .line 618
    .line 619
    .line 620
    .line 621
    .line 622
    .line 623
    .line 624
    .line 625
    .line 626
    .line 627
    .line 628
    .line 629
    .line 630
    .line 631
    .line 632
    .line 633
    .line 634
    .line 635
    .line 636
    .line 637
    .line 638
    .line 639
    .line 640
    .line 641
    .line 642
    .line 643
    .line 644
    .line 645
    .line 646
    .line 647
    .line 648
    .line 649
    .line 650
    .line 651
    .line 652
    .line 653
    .line 654
    .line 655
    .line 656
    .line 657
    .line 658
    .line 659
    .line 660
    .line 661
    .line 662
    .line 663
    .line 664
    .line 665
    .line 666
    .line 667
    .line 668
    .line 669
    .line 670
    .line 671
    .line 672
    .line 673
    .line 674
    .line 675
    .line 676
    .line 677
    .line 678
    .line 679
    .line 680
    .line 681
    .line 682
    .line 683
    .line 684
    .line 685
    .line 686
    .line 687
    .line 688
    .line 689
    .line 690
    .line 691
    .line 692
    .line 693
    .line 694
    .line 695
    .line 696
    .line 697
    .line 698
    .line 699
    .line 700
    .line 701
    .line 702
    .line 703
    .line 704
    .line 705
    .line 706
    .line 707
    .line 708
    .line 709
    .line 710
    .line 711
    .line 712
    .line 713
    .line 714
    .line 715
    .line 716
    .line 717
    .line 718
    .line 719
    .line 720
    .line 721
    .line 722
    .line 723
    .line 724
    .line 725
    .line 726
    .line 727
    .line 728
    .line 729
    .line 730
    .line 731
    .line 732
    .line 733
    .line 734
    .line 735
    .line 736
    .line 737
    .line 738
    .line 739
    .line 740
    .line 741
    .line 742
    .line 743
    .line 744
    .line 745
    .line 746
    .line 747
    .line 748
    .line 749
    .line 750
    .line 751
    .line 752
    .line 753
    .line 754
    .line 755
    .line 756
    .line 757
    .line 758
    .line 759
    .line 760
    .line 761
    .line 762
    .line 763
    .line 764
    .line 765
    .line 766
    .line 767
    .line 768
    .line 769
    .line 770
    .line 771
    .line 772
    .line 773
    .line 774
    .line 775
    .line 776
    .line 777
    .line 778
    .line 779
    .line 780
    .line 781
    .line 782
    .line 783
    .line 784
    .line 785
    .line 786
    .line 787
    .line 788
    .line 789
    .line 790
    .line 791
    .line 792
    .line 793
    .line 794
    .line 795
    .line 796
    .line 797
    .line 798
    .line 799
    .line 800
    .line 801
    .line 802
    .line 803
    .line 804
    .line 805
    .line 806
    .line 807
    .line 808
    .line 809
    .line 810
    .line 811
    .line 812
    .line 813
    .line 814
    .line 815
    .line 816
    .line 817
    .line 818
    .line 819
    .line 820
    .line 821
    .line 822
.end method

.method public static final A01(LX/1dV;I)Ljava/util/HashMap;
    .locals 3

    .line 0
    const/4 v0, 0x0

    .line 1
    invoke-static {p0, v0}, LX/02K;->A0A(Ljava/lang/Object;I)V

    .line 2
    .line 3
    .line 4
    new-instance v2, Ljava/util/HashMap;

    .line 5
    .line 6
    invoke-direct {v2}, Ljava/util/HashMap;-><init>()V

    .line 7
    .line 8
    .line 9
    iget v0, p0, LX/1dV;->A00:I

    .line 10
    .line 11
    invoke-static {v0}, Ljava/lang/String;->valueOf(I)Ljava/lang/String;

    .line 12
    .line 13
    .line 14
    move-result-object v1

    .line 15
    const-string v0, "optimization_type"

    .line 16
    .line 17
    invoke-virtual {v2, v0, v1}, Ljava/util/AbstractMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    .line 18
    .line 19
    .line 20
    invoke-static {p1}, Ljava/lang/String;->valueOf(I)Ljava/lang/String;

    .line 21
    .line 22
    .line 23
    move-result-object v1

    .line 24
    const-string v0, "option_value"

    .line 25
    .line 26
    invoke-virtual {v2, v0, v1}, Ljava/util/AbstractMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    .line 27
    .line 28
    .line 29
    return-object v2
    .line 30
    .line 31
.end method
